# calculate_bmi_features.yaml

# Inputs
bmi_medication_path: data/processed/bmi_medication.parquet
diagnosis_path: data/interim/diagnosis_final_intervals.parquet

# Output
output_file: data/processed/bmi_medication_diagnosis.parquet

# Column name mappings
patientid_col: PatientDurableKey
bmi_instant_col: CreateInstant
start_col: DiagnosisStartDate
discontinued_col: DiagnosisEndDate
sks_range_col: SKSCodes_range
sks_col: SKSCode
birth_date_col: BirthDate

# Number of parallel workers for sks mapping
num_processes: 16