# combine_bmi_hospitalization.yaml

# Inputs
bmi_path: data/processed/bmi_medication_diagnosis_labtests.parquet
hospitalization_path: data/interim/hospitalAdmission_cleaned.parquet

# Outputs
output_file: data/processed/bmi_medication_diagnosis_labtests_hospitalization.parquet

# Column name mappings
patientid_col: PatientDurableKey
bmi_instant_col: CreateInstant
start_col: InpatientAdmissionInstant
end_col: DischargeInstant
hosp_key_col: HospitalAdmissionKey
hosp_service_col: HospitalService