# config/synthetic.yaml

# random seed for reproducibility
random_seed: 2000

# number of synthetic patients
n_patients: 1000

# output directory for parquet files
output_dir: data/synthetic/

# which tables to generate
tables:
  patients: true
  healthAssessment: true
  diagnosis: true
  medication: true
  labComponentResults: true
  hospitalAdmission: true
  familyHistory: true

