# config for LOWESS comparison plot

tables:
  df1: data/processed/cohort_wot_olanzapine_last.parquet
  df2: data/processed/cohort_on_olanzapine_last.parquet

outs: data/plots

plot_specs:
  age_col: healthAssesment_age
  value_col: BodyMassIndex_recalc
  label1: "Olanzapine: False"
  label2: "Olanzapine: True"
  frac: 0.1
  figsize: [4, 4]
  outfile: olanzapine_with_wot_bmi_lowess_compare_last.png
