# preprocess_medication_dosage.yaml

# input/output
input_file: data/interim/medication_cleaned.parquet
output_file: data/interim/medication_filtered_dosages.parquet

# dosage_filtering parameters - accepted medication dosage ranges
atc_col: ATC
strength_col: StrengthNumeric
dosage_ranges:
  N05AD08: [10, 20]      # Droperidol
  N05AH04: [150, 800]    # Quetiapine
  N05AH03: [2.5, 40]     # Olanzapine
  N05AX12: [10, 30]      # Aripiprazole
  N05AD01: [2, 20]       # Haloperidol
  N05AX08: [1, 16]       # Risperidone
  N05AF03: [100, 800]    # Chlorprothixene
  N05AX13: [3, 12]       # Paliperidone
  N05AF05: [10, 150]     # Zuclopenthixol
  N05AH02: [100, 900]    # Clozapine

# clean_medication_frequency parameters
frequency_col: Frequency



