# preprocess_medication_olanzapine.yaml

# Input
bmi_demographics_path: data/processed/bmi_demographics.parquet
medication_path: data/interim/medication_calculated_features.parquet
integrated_data_path: data/processed/integrated_data.parquet

# Output
olanzapine_info_path: data/processed/olanzapine_info.parquet
before_olanzapine_path: data/processed/bmi_before_olanzapine.parquet
first_on_olanzapine_path: data/processed/bmi_first_on_olanzapine.parquet
last_on_olanzapine_path: data/processed/bmi_last_on_olanzapine.parquet

# Column name mappings
patientid_col: PatientDurableKey
bmi_instant_col: CreateInstant
atc_col: ATC
start_col: StartInstant
discontinued_col: DiscontinuedInstant
dosage_col: StrengthNumerica
dosage_daily_col: StrengthNumeric_daily