# preprocess_medication_intervals.yaml

# base input directory for raw parquet files
input_file: data/interim/medication_filtered_dosages.parquet

# base output directory for cleaned parquet files
output_file: data/interim/medication_final_intervals.parquet

# medication intervals function parameters
patientid_col: PatientDurableKey
dosage_col: Strength
dosage_num_col: StrengthNumeric
atc_col: ATC
start_col: StartInstant
discontinued_col: DiscontinuedInstant
frequency_col: Frequency
dosage_daily_col: StrengthNumeric_daily