# preprocess_medication_features.yaml

# base input directory for raw parquet files
input_file: data/interim/medication_final_intervals.parquet

# base output directory for cleaned parquet files
output_file: data/interim/medication_calculated_features.parquet

# extract function parameters
patientid_col: PatientDurableKey
atc_col: ATC
start_col: StartInstant
discontinued_col: DiscontinuedInstant




