# calculate_bmi_features.yaml

# Inputs
bmi_demographics_path: data/processed/bmi_demographics.parquet
medication_path: data/interim/medication_calculated_features.parquet

# Output
output_file: data/processed/bmi_medication.parquet

# Column name mappings
patientid_col: PatientDurableKey
bmi_instant_col: CreateInstant
start_col: StartInstant
discontinued_col: DiscontinuedInstant
atc_col: ATC
birth_date_col: BirthDate


# Number of parallel workers for atc mapping
num_processes: 16