# plot_distributions.yaml
# Configuration file for plotting distributions of variables

# list of input tables (parquet files)
tables:
  cohort_on_olanzapine_first: data/processed/cohort_on_olanzapine_first.parquet
  cohort_wot_olanzapine_first: data/processed/cohort_wot_olanzapine_first.parquet

outs: data/plots

sex_palette:
  0: "#9fb3ef"   # male
  1: "#f2a9bf"   # female

hist_bins: 40
figsize: [7, 7]

# plot specifications
plot_specs:
  healthAssesment_age:
    title: "Age Distribution by Sex (years)"
    xlabel: "Age (years)"
    suffix: "age_distribution.png"

  BodyMassIndex_recalc:
    title: "BMI Distribution by Sex (kg/m²)"
    xlabel: "BMI (kg/m²)"
    suffix: "bmi_distribution.png"

  CreateInstant:
    title: "Distribution of the Dates of BMI Records"
    xlabel: "Date (dd/mm/yyyy)"
    suffix: "bmi_dates_distribution.png"

  BMI_Variance_History:
    title: "BMI Variance History Distribution"
    xlabel: "BMI Variance (kg/m²)"
    suffix: "bmi_variance_distribution.png"

  bmi_diff_timepass_from_next:
    title: "Distribution of the Time Until Next Visit"
    xlabel: "Time in days"
    suffix: "bmi_time_until_next.png"

  BMI_distance_from_StartInstant:
    title: "Distribution of the Time From Olanzapine Start"
    xlabel: "Time in days"
    suffix: "bmi_time_from_start.png"
